var num1 = 20;
var num2 = 40;
var result;
result = num1 + num2;
console.log("sum:" + result);
result = num1 - num2;
console.log("sub:" + result);
result = num1 * num2;
console.log("mul:" + result);
result = num1 / num2;
console.log("div: " + result);
result = num1 % num2;
console.log("Remainder: " + result);
num1++;
console.log("Value of num1 after increment: " + num1);
num2--;
console.log("Value of num2 after decrement: " + num2);
